config/routes.rb
Rails.application.routes.draw do

  get 'fish/new_member_fish' => 'fish#new_member_fish'
  resources :fish

  get 'fishing_trip_members/member_fishing_trips' => 'fishing_trip_members#member_fishing_trips'
  get 'fishing_trip_members/member_fishing_trip' => 'fishing_trip_members#member_fishing_trip'
  resources :members

  get 'main/index'

  resources :species

  resources :fishing_trips

  root 'main#index'

end

app/models/fishing_trip.rb
class FishingTrip < ActiveRecord::Base
  has_many :fishing_trip_members
  has_many :members, through: :fishing_trip_members
  accepts_nested_attributes_for :members
  accepts_nested_attributes_for :fishing_trip_members

  validates_presence_of :members, :name
  validates_uniqueness_of :name
end

app/controllers/fishing_trips_controller.rb
class FishingTripsController < ApplicationController
  before_action :set_fishing_trip, only: [:show, :edit, :update, :destroy]

  # GET /fishing_trips
  # GET /fishing_trips.json
  def index
    @fishing_trips = FishingTrip.all
  end

  # GET /fishing_trips/1
  # GET /fishing_trips/1.json
  def show
    @fishing_trip = FishingTrip.find(params[:id])
    @members = @fishing_trip.members
  end

  # GET /fishing_trips/new
  def new
    @members = Member.all.order(last_name: :asc)
    @fishing_trip = FishingTrip.new
  end

  # GET /fishing_trips/1/edit
  def edit
    @fishing_trip = FishingTrip.find(params[:id])
    @members = @fishing_trip.members
  end

  # POST /fishing_trips
  # POST /fishing_trips.json
  def create
    @fishing_trip = FishingTrip.new(fishing_trip_params)

    respond_to do |format|
      if @fishing_trip.save
        format.html { redirect_to root_path, notice: 'Fishing trip was successfully created.' }
        format.json { render :show, status: :created, location: @fishing_trip }
      else
        format.html { render :new }
        format.json { render json: @fishing_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fishing_trips/1
  # PATCH/PUT /fishing_trips/1.json
  def update
    respond_to do |format|
      if @fishing_trip.update(fishing_trip_params)
        format.html { redirect_to @fishing_trip, notice: 'Fishing trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @fishing_trip }
      else
        format.html { render :edit }
        format.json { render json: @fishing_trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fishing_trips/1
  # DELETE /fishing_trips/1.json
  def destroy
    @fishing_trip.destroy
    respond_to do |format|
      format.html { redirect_to fishing_trips_url, notice: 'Fishing trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_fishing_trip
    @fishing_trip = FishingTrip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def fishing_trip_params
    params.require(:fishing_trip).permit(:id, :name, :member_ids => [])
  end
end

app/helpers/fishing_trips_helper.rb
module FishingTripsHelper
end

app/views/fishing_trips/_form.html.erb
<%= simple_form_for @fishing_trip do |sf| %>
    <%= sf.error_notification %>
    <%= sf.input :name %>
    <%= sf.association :members, label_method: :formatted_name, value_method: :id, as: :check_boxes %>
    <%= sf.button :submit %>
<% end %>

app/views/fishing_trips/edit.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Editing Fishing Trip</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', fishing_trips_path %></p>
  <%= render 'form' %>
</div>

app/views/fishing_trips/index.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Fishing Trips</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'New Fishing Trip', new_fishing_trip_path %></p>
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <!--<th>ID</th>-->
        <th>Name</th>
        <!--<th>Date</th>-->
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @fishing_trips.each do |fishing_trip| %>
          <tr>
            <!--<td><%= fishing_trip.id %></td>-->
            <td><%= fishing_trip.name %></td>
            <!--<td><%= fishing_trip.created_at.to_s %></td>-->
            <td><%= link_to 'View', fishing_trip %></td>
            <td><%= link_to 'Edit', edit_fishing_trip_path(fishing_trip) %></td>
            <!--<td><%= link_to 'Destroy', fishing_trip, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/fishing_trips/new.html.erb
<div class="panel-heading">
  <h4 class="panel-title">New Fishing Trip</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', fishing_trips_path %></p>
  <%= render 'form' %>
</div>

app/views/fishing_trips/show.html.erb
<!--
<div class="panel-heading">
  <h4 class="panel-title">
    Fishing Trip: #<%= @fishing_trip.id.to_s %>,
    Name: <%= @fishing_trip.name %>,
    Date: <%= @fishing_trip.created_at.to_s %>
  </h4>
</div>
<div class="panel-body">
  <p><%= link_to "Add Fish", new_fish_path %></p>
  <% @members.each do |member| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h5 class="panel-title"><%= member.first_name %> <%= member.last_name %></h5>
        </div>
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
              <tr>
                <th>Species</th>
                <th>Count</th>
              </tr>
              </thead>
              <tbody>
              <% if member.species_count_hash.any? %>
        <% member.species_count_hash.each { |key, value| %>
                      <tr>
                        <td><%= key.name %></td>
                        <td><%= value %></td>
                      </tr>
                  <% } %>
    <% else %>
                  <tr>
                    <td>None</td>
                    <td>0</td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
  <% end %>
</div>
-->
<ul class="list-group">
  <li class="list-group-item disabled">
    <strong>
      Fishing Trip: #<%= @fishing_trip.id.to_s %>,
      Name: <%= @fishing_trip.name %>,
      Date: <%= @fishing_trip.created_at.to_s %>
    </strong>
  </li>
  <li class="list-group-item">
    <%= link_to "Add Fish", new_fish_path %>
  </li>
  <% @members.each do |member| %>
      <li class="list-group-item disabled">
        <strong>
          <%= member.first_name %> <%= member.last_name %>
        </strong>
      </li>
      <% if member.species_count_hash.any? %>
          <% member.species_count_hash.each { |key, value| %>
              <li class="list-group-item">
                <%= key.name %>
                <span class="badge">
                  <%= value %>
                </span>
              </li>
          <% } %>
      <% end %>
  <% end %>
</ul>