config/routes.rb
Rails.application.routes.draw do

  get 'fish/new_member_fish' => 'fish#new_member_fish'
  resources :fish

  get 'fishing_trip_members/member_fishing_trips' => 'fishing_trip_members#member_fishing_trips'
  get 'fishing_trip_members/member_fishing_trip' => 'fishing_trip_members#member_fishing_trip'
  resources :members

  get 'main/index'

  resources :species

  resources :fishing_trips

  root 'main#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FishOn</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <nav class="navbar navbar-default">
    <div class="navbar-header">
      <ul class="nav nav-pills">
        <li><%= link_to 'Main', main_index_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Indexes <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Members', members_path %></li>
            <li><%= link_to 'Fishing Trips', fishing_trips_path %></li>
            <li><%= link_to 'Species', species_index_path %></li>
            <li><%= link_to 'Fish', fish_index_path %></li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
  <p id="notice"><%= notice %></p>

  <div class="panel panel-default">
    <%= yield %>
  </div>
</div>
</body>
</html>