config/routes.rb
Rails.application.routes.draw do

  get 'fish/new_member_fish' => 'fish#new_member_fish'
  resources :fish

  get 'fishing_trip_members/member_fishing_trips' => 'fishing_trip_members#member_fishing_trips'
  get 'fishing_trip_members/member_fishing_trip' => 'fishing_trip_members#member_fishing_trip'
  resources :members

  get 'main/index'

  resources :species

  resources :fishing_trips

  root 'main#index'

end

app/models/member.rb
class Member < ActiveRecord::Base
  #has_secure_password
  has_many :fish
  has_many :fishing_trip_members
  has_many :fishing_trips, through: :fishing_trip_members
  accepts_nested_attributes_for :fishing_trips
  accepts_nested_attributes_for :fishing_trip_members

  validates_presence_of :first_name, :last_name#, :email

  def self.available_members(user_id)
    Member.where.not(id: user_id).where(active: true)
  end

  def self.active_members
    Member.where(active: true)
  end

  def self.members_map
    Member.all.order(last_name: :asc).map{ |member| [ member.formatted_name, member.id ] }
  end

  def formatted_name
    @name = self.last_name + ', ' + self.first_name
  end

  def species_caught_ids
    @species_ids = self.fish.pluck(:species_id)
  end

  def species_caught_names
    @species_names = Species.where(id: self.species_caught_ids).pluck(:name)
  end

  def species_count(species_id)
    self.fish.where(species_id: species_id).count
  end

  def species_count_hash
    species_hash = Hash.new
    species_caught_ids.each do |id|
      species_hash[Species.find(id)] = species_count(id)
    end
    species_hash
  end

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= simple_form_for @member do |sf| %>
    <%= sf.error_notification %>
    <%= sf.input :first_name %>
    <%= sf.input :last_name %>
    <!--
    <%= sf.input :email %>
    <%= sf.input :password %>
    <%= sf.input :password_confirmation %>
    -->
    <%= sf.button :submit %>
<% end %>

app/views/members/edit.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Editing Member</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', members_path %></p>
  <%= render 'form' %>
</div>

app/views/members/index.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Members</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'New Member', new_member_path %></p>
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <!--<th>Email</th>-->
        <th>Fishing Trips</th>
        <th colspan="2">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @members.each do |member| %>
          <tr>
            <td><%= member.first_name %></td>
            <td><%= member.last_name %></td>
            <!--<td><%= member.email %></td>-->
            <td><%= link_to 'Fishing Trips', fishing_trip_members_member_fishing_trips_path(id: member.id) %></td>
            <td><%= link_to 'View', member %></td>
            <td><%= link_to 'Edit', edit_member_path(member) %></td>
            <!--<td><%= link_to 'Destroy', member, method: :delete, data: {confirm: 'Are you sure?'} %></td>-->
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/members/new.html.erb
<div class="panel-heading">
  <h4 class="panel-title">New Member</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', members_path %></p>
  <%= render 'form' %>
</div>

app/views/members/show.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Viewing Member</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', members_path %></p>
  <ul class="list-group">
    <!--
    <li class="list-group-item">
      <h4 class="list-group-item-heading">ID</h4>
      <h5 class="list-group-item-text"><%= @member.id %></h5>
    </li>
    -->
    <li class="list-group-item">
      <h4 class="list-group-item-heading">First Name</h4>
      <h5 class="list-group-item-text"><%= @member.first_name %></h5>
    </li>
    <li class="list-group-item">
      <h4 class="list-group-item-heading">Last Name</h4>
      <h5 class="list-group-item-text"><%= @member.last_name %></h5>
    </li>
    <!--
    <li class="list-group-item">
    <h4 class="list-group-item-heading">Email</h4>
    <h5 class="list-group-item-text"><%= @member.email %></h5>
    </li>
    -->
  </ul>
</div>