config/routes.rb
Rails.application.routes.draw do

  get 'fish/new_member_fish' => 'fish#new_member_fish'
  resources :fish

  get 'fishing_trip_members/member_fishing_trips' => 'fishing_trip_members#member_fishing_trips'
  get 'fishing_trip_members/member_fishing_trip' => 'fishing_trip_members#member_fishing_trip'
  resources :members

  get 'main/index'

  resources :species

  resources :fishing_trips

  root 'main#index'

end

app/models/fish.rb
class Fish < ActiveRecord::Base
  belongs_to :species
  belongs_to :member
  belongs_to :fishing_trip

  validates_presence_of :ipl, :fpl, :species, :member, :fishing_trip
  validates :ipl, numericality: { greater_than_or_equal_to: 0 }

  def length
    MathUtils.combine_length(self.ipl, self.fpl)
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]

  # GET /fish
  # GET /fish.json
  def index
    @fish = Fish.all
  end

  # GET /fish/1
  # GET /fish/1.json
  def show
  end

  # GET /fish/new
  def new
    @fish = Fish.new
    @members = Member.members_map
    @species = Species.species_map
    @decimals = MathUtils.fish_length_decimals
  end

  def new_member_fish
    @fish = Fish.new
    @member = Member.find(params[:member_id])
    @fishing_trip = FishingTrip.find(params[:fishing_trip_id])
    @species = Species.species_map
    @decimals = MathUtils.fish_length_decimals
  end

  # GET /fish/1/edit
  def edit
    @fish = Fish.find(params[:id])
    @members = Member.members_map
    @species = Species.species_map
    @decimals = MathUtils.fish_length_decimals
  end

  # POST /fish
  # POST /fish.json
  def create
    @fish = Fish.new(fish_params)
    @fishing_trip = FishingTrip.find(@fish.fishing_trip_id)
    respond_to do |format|
      if @fish.save
        format.html { redirect_to @fishing_trip, notice: 'Fish was successfully created.' }
        format.json { render :show, status: :created, location: @fish }
      else
        format.html { render :new }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fish/1
  # PATCH/PUT /fish/1.json
  def update
    respond_to do |format|
      if @fish.update(fish_params)
        format.html { redirect_to @fish, notice: 'Fish was successfully updated.' }
        format.json { render :show, status: :ok, location: @fish }
      else
        format.html { render :edit }
        format.json { render json: @fish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fish/1
  # DELETE /fish/1.json
  def destroy
    @fish.destroy
    respond_to do |format|
      format.html { redirect_to fish_index_url, notice: 'Fish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fish
      @fish = Fish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fish_params
      params.require(:fish).permit(:id, :species_id, :member_id, :fishing_trip_id, :ipl, :fpl)
    end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= simple_form_for @fish do |sf| %>
    <%= sf.error_notification %>
    <%= sf.association :species, label_method: :name, value_method: :id, include_blank: false %>
    <%= sf.association :member, label_method: :formatted_name, value_method: :id, include_blank: false %>
    <%= sf.association :fishing_trip, label_method: :name, value_method: :id, include_blank: false %>
    <%= sf.input :ipl, input_html: { min: '0', step: 'any' }, label: 'Length' %>
    <%= sf.input :fpl, collection: @decimals, label: 'Remainder', as: :select %>
    <%= sf.button :submit %>
<% end %>

app/views/fish/_show.html.erb
<ul class="list-group">
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Species</h4>
    <h5 class="list-group-item-text"><%= link_to @fish.species.name, @fish.species %></h5>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Member</h4>
    <h5 class="list-group-item-text">
      <%= link_to @fish.member.formatted_name, @fish.member %>
    </h5>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Fishing Trip</h4>
    <h5 class="list-group-item-text">
      <%= link_to @fish.fishing_trip.created_at.to_s, @fish.fishing_trip %>
    </h5>
  </li>
  <li class="list-group-item">
    <h4 class="list-group-item-heading">Length</h4>
    <h5 class="list-group-item-text"><%= @fish.length %></h5>
  </li>
</ul>

app/views/fish/edit.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Editing Fish</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', fish_index_path %></p>
  <%= render 'form' %>
</div>

app/views/fish/index.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Fish</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'New Fish', new_fish_path %></p>
  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <th>Species</th>
        <th>Member</th>
        <th>Fishing Trip</th>
        <th>Length</th>
        <th colspan="3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @fish.each do |fish| %>
          <tr>
            <td><%= fish.species.name %></td>
            <td><%= fish.member.formatted_name %></td>
            <td><%= fish.fishing_trip.id %></td>
            <td><%= fish.length %></td>
            <td><%= link_to 'View', fish %></td>
            <td><%= link_to 'Edit', edit_fish_path(fish) %></td>
            <td><%= link_to 'Destroy', fish, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/fish/new.html.erb
<div class="panel-heading">
  <h4 class="panel-title">New Fish</h4>
</div>
<div class="panel-body">
  <%= render 'form' %>
</div>

app/views/fish/new_member_fish.html.erb
<div class="panel-heading">
  <h4 class="panel-title">
    New Fish for: <%= @member.first_name + " " + @member.last_name %><br>
    Fishing Trip #<%= @fishing_trip.id.to_s %><br>
    Date: <%= @fishing_trip.created_at.to_s %>
  </h4>
</div>
<div class="panel-body">
  <%= form_for(@fish) do |f| %>
      <% if @fish.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

            <ul>
              <% @fish.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :species_id %><br>
        <%= f.select(:species_id, @species) %>
      </div>
      <div class="field">
        <%= f.label 'Length' %><br>
        <%= f.text_field :ipl %>
      </div>
      <div class="field">
        <%= f.label 'Remainder' %><br>
        <%= f.select(:fpl, @decimals) %>
      </div>
      <div class="actions">
        <%= f.submit 'Add' %>
      </div>
  <% end %>
</div>

app/views/fish/show.html.erb
<div class="panel-heading">
  <h4 class="panel-title">Viewing Fish</h4>
</div>
<div class="panel-body">
  <p><%= link_to 'Index', fish_index_path %></p>
  <%= render 'show' %>
</div>